apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: cnnamani/reverseproxy:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: envconfig
        - secretRef:
            name: aws-secret
        - secretRef:
            name: envsecret
