version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            echo "$PWD"
            docker build -t udagram-api-feed ././udagram-api-feed
            docker build -t udagram-api-user ././udagram-api-user
            docker build -t udagram-api-frontend ././udagram-api-frontend
            docker build -t reverseproxy ././reverseproxy

            docker tag udagram-api-feed cnnamani/udagram-api-feed:v1
            docker tag udagram-api-user cnnamani/udagram-api-user:v1
            docker tag udagram-api-frontend cnnamani/udagram-frontend:v1
            docker tag reverseproxy cnnamani/reverseproxy:v1
  publish-latest:
    docker:
      - image: node:12
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push cnnamani/udagram-api-feed:v1
            docker push cnnamani/udagram-api-user:v1
            docker push cnnamani/udagram-frontend:v1
            docker push cnnamani/reverseproxy:v1
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main
