version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker images
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            echo "$PWD"
            docker build -t udagram-api-feed ././udagram-api-feed
            docker build -t udagram-api-user ././udagram-api-user
            docker build -t udagram-frontend ././udagram-frontend
            docker build -t reverseproxy ././udagram-reverseproxy
      - run:
          name: Tag Docker Images
          command: |
            docker tag udagram-api-feed cnnamani/udagram-api-feed:v1
            docker tag udagram-api-user cnnamani/udagram-api-user:v1
            docker tag udagram-frontend cnnamani/udagram-frontend:v1
            docker tag reverseproxy cnnamani/reverseproxy:v1
      - run:
          name: Push Docker Images to Dockerhub
          command: |
            docker push cnnamani/udagram-api-feed:v1
            docker push cnnamani/udagram-api-user:v1
            docker push cnnamani/udagram-frontend:v1
            docker push cnnamani/reverseproxy:v1
            
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
