orbs:
 docker: circleci/docker@1.5.0
version: 2.1
executors:
 docker-publisher: 
 environment:
 IMAGE_NAME: ndukwearm19docker/docker-node-app
 docker: # Each job requires specifying an executor
 # (either docker, macos, or machine), see
 — image: circleci/node:latest
 auth:
 username: $DOCKERHUB_USERNAME
 password: $DOCKERHUB_PASSWORD
jobs:
 publishLatestToHub: 
 executor: docker-publisher
 
 steps: 
 — checkout
 — setup_remote_docker
 — run: 
 name: Publish Docker Image to Docker Hub
 command: |
 echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” — password-stdin
 
 docker build -t udagram-api-feed ./udagram-api-feed
 docker build -t udagram-api-user ./udagram-api-user
 docker build -t udagram-api-frontend ./udagram-api-frontend
 docker build -t reverseproxy ./reverseproxy
 
 docker tag udagram-api-feed cnnamani/udagram-api-feed:v1
 docker tag udagram-api-user cnnamani/udagram-api-user:v1
 docker tag udagram-api-frontend cnnamani/udagram-frontend:v1
 docker tag reverseproxy cnnamani/reverseproxy:v1
 
 docker push cnnamani/udagram-api-feed:v1
 docker push cnnamani/udagram-api-user:v1
 docker push cnnamani/udagram-frontend:v1
 docker push cnnamani/reverseproxy:v1
workflows:
 version: 2
 build-master:
 jobs:
 — publishLatestToHub
